export const INITIAL_SPECS = {
  positionX: 0,
  positionY: 0,
  positionWidth: 60,
  positionHeight: 128,
  x: 0,
  y: 0,
  width: 70,
  height: 140,
  layerHeight: 180,
  fill: '#fff',
  image: null,
  sensitivity: 10,
  sensitivityMax: 10,
  sensitivityRatio: 1.5,
  deltaOffsetY: 0.5,
  rotate: 0,
  bottomOffset: 50,
}
