version: "3.9"

services:
  #############
  ## CLIENT ##
  client:
    container_name: prakticum-client
    image: ghcr.io/crazymaza/codebusters/client:935ffd20d9dd1eb5ba64636b3a87e59514cf98a6
    # build:
    #   context: .
    #   dockerfile: Dockerfile.client
    #   args:
    #     CLIENT_PORT: $CLIENT_PORT
    restart: always
    ports:
      - ":81"
    depends_on:
      - server
    environment:
      - CLIENT_PORT=$CLIENT_PORT
      - SERVER_PORT=$SERVER_PORT
    env_file: .env
    networks:
      - codebusters
    # command: [ "nginx", "-g", "daemon off;" ]
  #############
  ## SERVER ##
  server:
    container_name: prakticum-server
    image: ghcr.io/crazymaza/codebusters/server:ec189ff17d5d29a7f90da6c5e937b28016ee281a
    # build:
      # context: .
      # dockerfile: Dockerfile.server
      # args:
      #   SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - ":${SERVER_PORT}"
      - ":${VITE_PORT}"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_HOST=$POSTGRES_DB
    env_file: .env
    networks:
      - codebusters
    command: ["./wait-for.sh", "${POSTGRES_DB}:${POSTGRES_PORT}", "--", "node", "/app/index.js" ]
  ##############
  ## POSTGRES ##
  postgres:
    image: postgres:14
    ports:
      - ":${POSTGRES_PORT}"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB 
    env_file: .env
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
    networks:
      - codebusters
  ##############
  ## PGADMIN ##
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 802
    ports:
      - ":802"
    depends_on:
      - postgres
    networks:
      - codebusters
    tty: true
  ##############
  ##  NGINX  ##
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:latest
    volumes:
      - ./utils/nginx.conf:/etc/nginx/nginx.conf
      - ./utils/certbot/www/:/var/www/certbot/:ro
      - ./utils/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    restart: always
    networks:
      - codebusters
    command: ["nginx", "-g", "daemon off;" ]
  ##############
  ## CERBOT ##
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./utils/certbot/www/:/var/www/certbot/:rw
    depends_on:
      - server
    networks:
      - codebusters
    command: certonly --noninteractive --keep-until-expiring --webroot --webroot-path=/var/www/html --email ${EMAIL_FOR_CERBOT} --agree-tos --no-eff-email --force-renewal -d ${SITE_ADDRESS}


networks:
  codebusters:
    driver: bridge
    