export const INITIAL_SPECS = {
  header: '',
  text: '',
  x: 0,
  y: 150,
  width: 496,
  height: 200,
  fontColor: '#eaeaea',
  strokeColor: '#eee',
  rectColor: '#565656',
  strokeWidth: 4,
  indent: 20,
  border: 10,
  lineSpacing: 70,
  textYAxisBegin: 80,
}
