name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: ghcr.io/crazymaza/codebusters/client:${{ github.sha }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ghcr.io/crazymaza/codebusters/server:${{ github.sha }} 
