name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Format repo lower case
        uses: actions/github-script@v4
        id: lower_repo
        with:
          result-encoding: string
          script: return `${github.event.repository.name.toLowerCase()}`
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.client
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.lower_repo.outputs.result }}/client:${{ github.sha }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.lower_repo.outputs.result }}/server:${{ github.sha }} 
